<?php
/**
 * @file
 * thisted_event_import.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function thisted_event_import_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-xml_event_import-field_library'
  $field_instances['node-xml_event_import-field_library'] = array(
    'bundle' => 'xml_event_import',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser_highlight' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_library',
    'label' => 'Library',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 31,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Library');

  return $field_instances;
}
